services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: mattermost
      POSTGRES_DB: mattermost
      POSTGRES_PASSWORD: mattermost

  mattermost:
    image: mattermost/mattermost-team-edition:11.10.1  # официальный образ Mattermost Team Edition
    depends_on:
      - postgres  # Mattermost запускается после создания контейнера PostgreSQL
    ports:
      - "8065:8065"  # порт Ubuntu:8065 -> порт Mattermost:8065
    environment:
      MM_SQLSETTINGS_DRIVERNAME: postgres  # говорим Mattermost использовать PostgreSQL
      MM_SQLSETTINGS_DATASOURCE: postgres://mattermost:mattermost@postgres:5432/mattermost?sslmode=disable&connect_timeout=10  # строка подключения к БД
